### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by anthonydahanne** [warmans/prometheus-aggregate-exporter#12]
Hello,
To make contributions welcome, I suggest a license should be picked.

Apache 2 is usually a good choice, but MIT too, or others non restrictive ones (there's a nice page helping to make a choice: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository)

Thank you!

**Comment by warmans** [comment]
Ah good point. I've added a LICENCE file (MIT).

**Comment by anthonydahanne** [comment]
thank you!
