### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by anthonydahanne** [warmans/prometheus-aggregate-exporter#15]
Hello,
If you apply PR #14 (in particular https://github.com/warmans/prometheus-aggregate-exporter/blob/c8a6f395c6bddee7c979dd033b958896f5470f19/Dockerfile), you'd get a simplified build process, allowing a 3rd party build mechanism such as DockerHub Automated builds to build and publish to Dockerhub the image every time there's a new commit merged.

Here is the documentation: https://docs.docker.com/docker-hub/builds/ ; I've done it a few times, I can help you with that if you want to.

I believe that would greatly simplify image comsumption
Thank you!

**Comment by warmans** [comment]
Hi, thanks for your changes. The project is a bit messy currently so stuff like this really helps. :)

I just added one comment to the MR.

**Comment by anthonydahanne** [comment]
hey there!

> I just added one comment to the MR.

 I could not find it? where is it?
thanks

**Comment by warmans** [comment]
Sorry, I'm dumb. I forgot to submit the review.

**Comment by anthonydahanne** [comment]
Np! Shall be fine now!

**Comment by warmans** [comment]
merged.

**Comment by anthonydahanne** [comment]
thanks for merging!!!

could you create a DockerHub automated build? we can chat about it if you want!

**Comment by warmans** [comment]
Sure, seems to work fine: https://hub.docker.com/repository/docker/warmans/prometheus-aggregate-exporter/builds  👍

**Comment by anthonydahanne** [comment]
got it! thanks so much!

I'll use `warmans/prometheus-aggregate-exporter` from now on DockerHub

https://hub.docker.com/r/warmans/prometheus-aggregate-exporter
