### ISSUE TITLE
= in target

### ISSUE THREAD

**Issue by francois-maillard** [warmans/prometheus-aggregate-exporter#16]
I'm trying to aggregate metrics from consul agent. As specified in the [doc](https://www.consul.io/api/agent#view-metrics), the metrics are exposed at `/v1/agent/metrics?format=prometheus`.

The code in [fetch](https://github.com/warmans/prometheus-aggregate-exporter/blob/master/cmd/main.go#L206) does not support `=` in a target url (I tested it by commenting out the `Split` call, but that's definitely not a solution:
```
    /*
    s := strings.Split(target, "=")
    url := s[0]
    name := s[0]
    if len(s) == 2 {
        url = s[1]
    }
    */
    url := target
    name := target
```

**Comment by warmans** [comment]
Hmm, I guess it's never really come up since the standard is usually just `/metrics`. If you want to open a MR I'm happy to tag a new version. Otherwise I might get around to looking into this at some point.

**Comment by francois-maillard** [comment]
I could not think of a clean solution except from changing the separator from `=` to something that wouldn't appear in a url... yet I just realized that something like this coud work;

```go
s := strings.Split(target, "=")
url := s[0]
name := s[0]
if len(s) > 1 {
    url = strings.Join(s[1:], "=")
}
```

I'll take the time to test that later on and will open a MR then.

**Comment by warmans** [comment]
Yeah think that would fix it. I guess the only problem is if you do not provide a name then it would split wrongly. But it already has that problem so at least this allows named URLs to work.

**Comment by francois-maillard** [comment]
Indeed, I thought I would just make that plain in the documentation.

**Comment by warmans** [comment]
I've pushed a new tag v2.1.1  The image on docker-hub should be created shortly.
