### ISSUE TITLE
Automatically upload binaries in the release

### ISSUE THREAD

**Issue by henri9813** [warmans/prometheus-aggregate-exporter#26]
Hello,

Can you upload automatically assets such as the binary for the `amd64`, `aarch64` like it's done on 
https://github.com/ricoberger/script_exporter/releases/tag/v2.20.1

I try to develop a script to automatically install the aggregator, but without "release", it's complicated.

thanks !

**Comment by warmans** [comment]
I've added amd64 linux/darwin binary artefacts. Tell me if you wanted some other GOOS/GOARCH combination.
