### ISSUE TITLE
Build without GLIBC dependency

### ISSUE THREAD

**Issue by vaz-ar** [warmans/prometheus-aggregate-exporter#30]
Hello,

I was wondering is there was a reason for linking dynamically with GLIBC ?
This is preventing the exporter to be use on systems with an older version of GLIBC.

I looked at other exporters like node exporter, and it is built wihtout CGO for amd64 platforms, which removes the GLIBC dependency (https://github.com/prometheus/node_exporter/blob/49d177bf95417b117ab612a376e2434d5dd61c2d/Makefile#L48-L59)

I am currently testing a version I built without CGO (by setting CGO_ENABLED=0) and so far I do not see any problem with it.

I can submit a pull request with a new make target if you are interested.

**Comment by warmans** [comment]
Sure submit a PR. There is likely no reason to include glibc.

**Comment by vaz-ar** [comment]
done, #31
