### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by adamdecaf** [warmans/prometheus-aggregate-exporter#4]
Hey! I'm looking at using this project, but I don't see a docker image. Could you release one? 

I looked on docker hub, but didn't see anything under the same username.  See: https://hub.docker.com/u/warmans

**Comment by warmans** [comment]
Sure, it would only take a couple of mins to add one. I'll try and do it after I finish work.

**Comment by warmans** [comment]
I've added all the files etc and pushed an image https://hub.docker.com/r/warmans/aggregate-exporter/

here is an example: https://github.com/warmans/prometheus-aggregate-exporter/blob/master/test/docker-compose.yml

The only issue is it uses a stupid config file which is annoying when deploying with docker. Someone could change the CLI interface to allow targets to be passed as args/environment variables and I would happily merge it.

**Comment by adamdecaf** [comment]
Awesome thanks! Using this in kubernetes it's easy to mount a `ConfigMap` into the container.
